// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var cache$, defaults, extend, fs, isEmpty, method, nopt, options, params, parseColonDelimitedPairs, Path, pnet;
  fs = require('fs');
  Path = require('path');
  nopt = require('nopt');
  defaults = require('./defaults');
  cache$ = require('underscore');
  extend = cache$.extend;
  isEmpty = cache$.isEmpty;
  parseColonDelimitedPairs = function (pairs) {
    var fn;
    if (null == pairs)
      pairs = [];
    fn = function (memo, param) {
      var cache$1, key, value;
      if (param.indexOf(':') !== -1) {
        cache$1 = param.split(':');
        key = cache$1[0];
        value = cache$1[1];
        memo[key] = value;
      }
      return memo;
    };
    return pairs.reduce(fn, {});
  };
  options = function () {
    var aliases, opts;
    opts = {
      configure: [
        String,
        Array
      ],
      date: String,
      method: String,
      output: String,
      params: [
        String,
        Array
      ]
    };
    aliases = {
      d: '--date',
      m: '--method',
      o: '--output',
      p: '--params'
    };
    return nopt(opts, aliases, process.argv, 1);
  }();
  if (options.help) {
    console.log("\n  USAGE: pnet OPT*\n\n  pnet -m shows.setlists.get -d 2013-10-31 -o ~/setlists/halloween_2013.json\n\n  -d, --date              Specify a `showdate` param to be used in API call.\n                          Shorthand for '-p showdate:YYYY-MM-DD'\n  -m, --method            The phish.net API method without the preceeding 'pnet.',\n                          for example, pnet.shows.query would be '-m shows.query'.\n                          Shorthand for '-p method:pnet.shows.query'\n  -o, --output            Output to file instead of STDOUT\n  -p, --params            Specify colon-delimited key value pairs as arguments to\n                          the phish.net API; i.e. '-p venueid:123456 -p year:2012'\n\n  --configure             Specify colon-delimited key value pairs to be used as\n                          defaults for all phish.net API calls through the CLI. i.e.\n                          '--configure apikey=your-api-key --configure api:2.0'\n  --defaults              Print the defaults that have been set via the --configure\n                          flag and exit\n  --help                  Display this message and exit\n  --url-only              Print phish net API url and exit instead of\n                          requesting the resource\n  --version               Print current version of this package and exit\n  ");
    process.exit(0);
  }
  if (options.version) {
    console.log(require(Path.join(__dirname, '../../package.json')).version);
    process.exit(0);
  }
  if (options.defaults) {
    console.log(JSON.stringify(defaults.get(), null, 4));
    process.exit(0);
  }
  if (options.configure) {
    defaults.set(parseColonDelimitedPairs(options.configure));
    process.exit(0);
  }
  params = extend(defaults.get(), parseColonDelimitedPairs(options.params));
  if (method = options.method) {
    if (!/^pnet\./.test(method))
      method = 'pnet.' + method;
    params.method = method;
  }
  if (isEmpty(params.method)) {
    console.error('ERROR: must specify a phish.net API method param');
    process.exit(1);
  }
  if (options.date)
    params.showdate = options.date;
  if (null != params.showdate && !/^\d{4}-\d{2}-\d{2}$/.test(params.showdate)) {
    console.error('ERROR: date must be in format YYYY-MM-DD');
    process.exit(1);
  }
  pnet = require(Path.join('..'));
  if (options['url-only']) {
    console.log(pnet.buildPhishNetUrl(params));
    process.exit(0);
  }
  pnet.get(params, function (err, resource) {
    var stringified;
    if (null != err) {
      console.error('ERROR requesting ' + err.url);
      console.error(null != err.message ? err.message : JSON.stringify(error));
      process.exit(1);
    }
    stringified = JSON.stringify(resource, null, 4);
    if (null != options.output) {
      fs.writeFileSync(options.output, stringified);
    } else {
      console.log(stringified);
    }
    return process.exit(0);
  });
}.call(this);
