// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var extend, fs, get, getDefaultsPath;
  fs = require('fs');
  extend = require('underscore').extend;
  getDefaultsPath = function () {
    return process.env.HOME + '/.pnet';
  };
  exports.get = get = function () {
    var e;
    try {
      return JSON.parse(fs.readFileSync(getDefaultsPath(), { encoding: 'utf8' }));
    } catch (e$) {
      e = e$;
      return {};
    }
  };
  exports.set = function (options) {
    var contents;
    if (null == options)
      options = {};
    contents = JSON.stringify(extend(get(), options), null, 4);
    return fs.writeFileSync(getDefaultsPath(), contents);
  };
}.call(this);
