// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var cache$, defaults, extend, fs, method, nopt, omit, options, PACKAGE_ROOT, params, parseColonDelimitedPairs, Path;
  fs = require('fs');
  Path = require('path');
  nopt = require('nopt');
  defaults = require('./defaults');
  cache$ = require('underscore');
  extend = cache$.extend;
  omit = cache$.omit;
  PACKAGE_ROOT = Path.join(__dirname, '..', '..', '..');
  parseColonDelimitedPairs = function (pairs) {
    if (null == pairs)
      pairs = [];
    return pairs.reduce(function (memo, param) {
      var cache$1, key, value;
      if (param.indexOf(':') !== -1) {
        cache$1 = param.split(':');
        key = cache$1[0];
        value = cache$1[1];
        memo[key] = value;
      }
      return memo;
    }, {});
  };
  options = function () {
    var aliases, opts;
    opts = {
      configure: [
        String,
        Array
      ],
      date: String,
      output: String,
      params: [
        String,
        Array
      ]
    };
    aliases = {
      d: '--date',
      o: '--output',
      p: '--params'
    };
    return nopt(opts, aliases, process.argv, 2);
  }();
  if (options.help) {
    console.log("\n  USAGE: pnet method [options]\n\n  pnet shows.setlists.get -d 2013-10-31 -o ~/setlists/halloween_2013.json\n\n  -d, --date              Specify a `showdate` param to be used in API call.\n                          Shorthand for '-p showdate:YYYY-MM-DD'\n  -o, --output            Output to file instead of STDOUT\n  -p, --params            Specify colon-delimited key value pairs as arguments to\n                          the phish.net API; i.e. '-p venueid:123456 -p year:2012'\n\n  --configure             Specify colon-delimited key value pairs to be used as\n                          defaults for all phish.net API calls through the CLI. i.e.\n                          '--configure apikey=your-api-key --configure api:2.0'\n  --defaults              Print the defaults that have been set via the --configure\n                          flag and exit\n  --list                  List the available phish.net API methods\n  --help                  Display this message and exit\n  --url-only              Print phish net API url and exit instead of\n                          requesting the resource\n  --version               Print current version of this package and exit\n  ");
    process.exit(0);
  }
  if (options.version) {
    console.log(require(PACKAGE_ROOT + '/package.json').version);
    process.exit(0);
  }
  if (options.defaults) {
    console.log(JSON.stringify(defaults.get(), null, 4));
    process.exit(0);
  }
  if (options.configure) {
    defaults.set(parseColonDelimitedPairs(options.configure));
    process.exit(0);
  }
  if (options.list) {
    (function (param$) {
      var cache$1, documentation, message, methods, protect, publicize;
      {
        cache$1 = param$;
        documentation = cache$1.documentation;
        methods = cache$1.methods;
      }
      publicize = function (str) {
        return '\x1b[32m' + str + '\x1b[39m';
      };
      protect = function (str) {
        return '\x1b[31m' + str + '\x1b[39m';
      };
      message = [
        'Documentation: ' + documentation.baseUrl + '\n',
        publicize('Public method'),
        protect('Protected method') + '\n'
      ].concat(function (accum$) {
        var line, method, spaces, status;
        for (method in methods) {
          if (!isOwn$(methods, method))
            continue;
          status = methods[method];
          line = (status['protected'] ? protect : publicize)(method);
          spaces = 45 - line.length;
          while (spaces--) {
            line += ' ';
          }
          accum$.push(line + documentation.baseUrl + ('/#p=' + method));
        }
        return accum$;
      }.call(this, []));
      return console.log('\n  ' + message.join('\n  ') + '\n');
    }(require(PACKAGE_ROOT + '/config').pnet.api));
    process.exit(0);
  }
  params = extend(defaults.get(), parseColonDelimitedPairs(options.params));
  method = null != options.argv.remain[0] ? options.argv.remain[0] : params.method;
  params = omit(params, 'method');
  if (options.date)
    params.showdate = options.date;
  require(PACKAGE_ROOT).get(method, params, function (err, url, resource) {
    var stringified;
    if (null != err) {
      console.error(null != err.message ? err.message : JSON.stringify(err));
      process.exit(1);
    }
    if (options['url-only']) {
      console.log(url);
      process.exit(0);
    }
    stringified = JSON.stringify(resource, null, 4);
    if (null != options.output) {
      fs.writeFileSync(options.output, stringified);
    } else {
      console.log(stringified);
    }
    return process.exit(0);
  });
  function isOwn$(o, p) {
    return {}.hasOwnProperty.call(o, p);
  }
}.call(this);
